<?php
return [
    'APP_VERSION' => '0.0.6',
    'PASS_EXPIRE' => 3628800,
    'PERMISSIONS_LIST_FACTORY' => array(
            'users_index',
            'users_edit',
            'users_create',
            'roles_index',
            'roles_edit',
            'roles_create',
            'permissions_index',
            'permissions_edit',
            'permissions_create',
            'dashborad_index',
            'dashborad_edit',
            'dashborad_create',
            'clientes_index',
            'clientes_edit',
            'clientes_create',
            'eventos_index',
            'eventos_edit',
            'eventos_create',
            'adicionales_index',
            'adicionales_edit',
            'adicionales_create',
            'reservas_index',
            'reservas_edit',
            'reservas_create',
    ),
    'ROLES_LIST_FACTORY' => array(
            'Admin',
            'Cliente',
            'Staff Admin',
            'Staff Ingreso',
            'Staff Barra'
    ),'CONTACT_EMAILS' => [
        'migvicpereyra@gmail.com',
        'cristian.g017@gmail.com',
        'patoelifer341@gmail.com',
    ],
];